version: "3.4"
services:
  boilerplate-api-unittests:
    image: boilerplate.api.unittests
    build:
      context: .
      dockerfile: ${BOILERPLATE_API_UNITTESTS}Dockerfile
      args:
        main: ${BOILERPLATE_API_UNITTESTS}
        api: ${BOILERPLATE_API}
    entrypoint:
      - dotnet
      - test
      - -l
      - trx;LogFileName=${TEST_RESULT_DIRECTORY}/TEST-api-unittests.xml
    volumes:
      - ${TEST_RESULT_DIRECTORY}:/${TEST_RESULT_DIRECTORY}