version: "3.4"
services:
  boilerplate-api-unittests:
    image: boilerplate.api.unittests
    build:
      context: .
      dockerfile: tests/Boilerplate.Api.UnitTests/Dockerfile
    environment: 
      BaseApiUrl: ${BaseApiUrl}
    entrypoint:
      - dotnet
      - test
      - /app/Boilerplate.Api.UnitTests.dll
      - -l
      - trx;LogFileName=${TEST_RESULT_DIRECTORY}/Boilerplate-api-unittests.xml
    volumes:
      - ${TEST_RESULT_DIRECTORY}:/${TEST_RESULT_DIRECTORY}

  boilerplate-api-integrationtests:
    image: boilerplate.api.integrationtests
    build:
      context: .
      dockerfile: tests/Boilerplate.Api.IntegrationTests/Dockerfile
    environment: 
      BaseApiUrl: ${BaseApiUrl}
    entrypoint:
      - dotnet
      - test
      - /app/Boilerplate.Api.IntegrationTests.dll
      - -l
      - trx;LogFileName=${TEST_RESULT_DIRECTORY}/Boilerplate-api-integrationtests.xml
    volumes:
      - ${TEST_RESULT_DIRECTORY}:/${TEST_RESULT_DIRECTORY}